# Generated by Django 2.2 on 2019-05-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='774265435412236639', max_length=255, primary_key=True, serialize=False),
        ),
    ]
