# Generated by Django 2.2 on 2019-04-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(default='767038368922483792', primary_key=True, serialize=False),
        ),
    ]
