# Generated by Django 2.2 on 2019-05-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190507_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='774279011166677926', max_length=255, primary_key=True, serialize=False),
        ),
    ]
