# Generated by Django 2.2 on 2019-04-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190428_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='767585970558155886', max_length=255, primary_key=True, serialize=False),
        ),
    ]
