# Generated by Django 2.2 on 2019-04-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190428_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='767666356187487108', max_length=255, primary_key=True, serialize=False),
        ),
    ]
